sudo: required
services:
    - docker

before_install:
    - docker build -t vipinatdocker/docker-react -f Dockerfile.dev .

script:
    - docker run vipinatdocker/docker-react npm run test -- --coverage
